version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: itsp-todo-app
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version && cargo --version && rustup --version
      - restore_cache:
          keys:
            - v1-cargo-lock-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Adding rustup components
          command: rustup component add rustfmt
      - run:
          name: Installing diesel_cli
          command: "cargo install diesel_cli --no-default-features --features postgres || echo \"exit status: $?\""
      - run:
          name: Installing dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Checking source code format
          command: cargo fmt -- --check
      - run:
          name: Building all targets
          command: cargo build --all --all-targets
      - save_cache:
          key: v1-cargo-lock-{{ arch }}-{{ checksum "Cargo.lock" }}
          paths:
            - "/usr/local/cargo/registory"
            - "/usr/local/cargo/bin/diesel"
            - "target"
      - run:
          name: Waiting for DB
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 60s
      - run:
          name: DB setup
          command: diesel setup
      - run:
          name: Running all tests
          command: RUST_BACKTRACE=1 cargo test --all
