version: 2

jobs:
  build:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version && cargo --version && rustup --version
      - run:
          name: Adding rustup components
          command: rustup component add rustfmt
      - run:
          name: Checking source code format
          command: cargo fmt -- --check
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ checksum "Cargo.lock" }}
      - run:
          name: Building all targets
          command: cargo build --all --all-targets
      - save_cache:
          key: v1-cargo-lock-{{ checksum "Cargo.lock" }}
          paths:
            - "/usr/local/cargo/registry"
            - "target"
      - run:
          name: Running all tests
          command: cargo test --all
